package com.codewithfk.shopper.ui.theme

import androidx.compose.ui.graphics.Color

//material colors

val primaryLight = Color(0xFF473ABE)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF6055D8)
val onPrimaryContainerLight = Color(0xFFEAE6FF)
val secondaryLight = Color(0xFF5C598C)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC8C3FE)
val onSecondaryContainerLight = Color(0xFF524F81)
val tertiaryLight = Color(0xFF892184)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFA63D9E)
val onTertiaryContainerLight = Color(0xFFFFE0F5)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFCF8FF)
val onBackgroundLight = Color(0xFF1B1B23)
val surfaceLight = Color(0xFFFCF8FF)
val onSurfaceLight = Color(0xFF1B1B23)
val surfaceVariantLight = Color(0xFFE4E0F3)
val onSurfaceVariantLight = Color(0xFF474554)
val outlineLight = Color(0xFF787585)
val outlineVariantLight = Color(0xFFC8C4D6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF312F38)
val inverseOnSurfaceLight = Color(0xFFF3EFFA)
val inversePrimaryLight = Color(0xFFC5C0FF)
val surfaceDimLight = Color(0xFFDCD8E4)
val surfaceBrightLight = Color(0xFFFCF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F2FD)
val surfaceContainerLight = Color(0xFFF0ECF8)
val surfaceContainerHighLight = Color(0xFFEAE6F2)
val surfaceContainerHighestLight = Color(0xFFE5E1EC)

val primaryDark = Color(0xFFC5C0FF)
val onPrimaryDark = Color(0xFF2504A0)
val primaryContainerDark = Color(0xFF6055D8)
val onPrimaryContainerDark = Color(0xFFEAE6FF)
val secondaryDark = Color(0xFFC5C0FB)
val onSecondaryDark = Color(0xFF2E2A5B)
val secondaryContainerDark = Color(0xFF444173)
val onSecondaryContainerDark = Color(0xFFB4AFE8)
val tertiaryDark = Color(0xFFFFABF1)
val onTertiaryDark = Color(0xFF5C0059)
val tertiaryContainerDark = Color(0xFFA63D9E)
val onTertiaryContainerDark = Color(0xFFFFE0F5)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF13131A)
val onBackgroundDark = Color(0xFFE5E1EC)
val surfaceDark = Color(0xFF13131A)
val onSurfaceDark = Color(0xFFE5E1EC)
val surfaceVariantDark = Color(0xFF474554)
val onSurfaceVariantDark = Color(0xFFC8C4D6)
val outlineDark = Color(0xFF928F9F)
val outlineVariantDark = Color(0xFF474554)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E1EC)
val inverseOnSurfaceDark = Color(0xFF312F38)
val inversePrimaryDark = Color(0xFF564ACD)
val surfaceDimDark = Color(0xFF13131A)
val surfaceBrightDark = Color(0xFF393841)
val surfaceContainerLowestDark = Color(0xFF0E0D15)
val surfaceContainerLowDark = Color(0xFF1B1B23)
val surfaceContainerDark = Color(0xFF201F27)
val surfaceContainerHighDark = Color(0xFF2A2931)
val surfaceContainerHighestDark = Color(0xFF35343C)